-- CreateTable
CREATE TABLE "EnglishWordPracPrint" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "title" TEXT NOT NULL,
    "memo" TEXT NOT NULL DEFAULT '',
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "EnglishWordPracPrintWord" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "print_id" INTEGER NOT NULL,
    "en_title" TEXT NOT NULL,
    "jp_title" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "EnglishWordPracPrintWord_print_id_fkey" FOREIGN KEY ("print_id") REFERENCES "EnglishWordPracPrint" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
